name: "Marcus Jekyll Theme"
title: "Marcus Jekyll theme"
description: "The Marcus Jekyll theme."
logo: 'assets/images/icon.png'
favicon: 'assets/images/icon.png'
baseurl: '/marcus'
permalink: /:year/:month/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pages
paginate: 6 # number of posts per page
paginate_path: /page:num/

# Exclude from processing when building site locally.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/