name: "Marcus Jekyll Theme"
title: "Marcus Jekyll theme"
description: "The Marcus Jekyll theme."
logo: 'assets/images/icon.png'
favicon: 'assets/images/icon.png'
baseurl: '/marcus'
permalink: /:year/:month/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/